// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Perfume.Api.Data;

#nullable disable

namespace Perfume.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719151415_FillData")]
    partial class FillData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Perfume.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fresh spicy",
                            ImageUrl = "~/images/sau.jpg",
                            NameAr = "سوفاج",
                            NameEn = "Sauvage",
                            Price = 64.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Warm sweet",
                            ImageUrl = "~/images/swy.jpg",
                            NameAr = "سترونجر ويذ يو",
                            NameEn = "Stronger With You",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Woody aromatic",
                            ImageUrl = "~/images/channel.jpg",
                            NameAr = "بلو دي شانيل",
                            NameEn = "Blue De Cannel",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Citrus fresh",
                            ImageUrl = "~/images/silver.jpg",
                            NameAr = "سيلفر سينت",
                            NameEn = "Silver Scent",
                            Price = 78.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nice smell",
                            ImageUrl = "~/images/boss.jpg",
                            NameAr = "بوس",
                            NameEn = "Boss Bottled",
                            Price = 33.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
